include("common.jl")
include("generic.jl")
include("wrapped_rng.jl")
include("PCG/runtests.jl")
include("MersenneTwisters/runtests.jl")
include("Xorshifts/runtests.jl")
include("Random123/runtests.jl")
